spring:
  application:
    name: NOTE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mynote?useUnicode=true&characterEncoding=UTF-8&servserTimezone=Asia/Shanghai
    username: root
    password: Ling
    hikari:
      #????
      pool-name: DateHikariCP
      #???????
      minimum-idle: 5
      #?????????? ??600000
      idle-timeout: 1800000
      #?????
      maximum-pool-size: 10
      #?????????????
      auto-commit: true
      #???????? 0?????????1800000
      max-lifetime: 1800000
      #?????? ??30000
      connection-timeout: 30000
      #?????????????
      connection-test-query: SELECT 1
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: true
logging:
  level:
    com.lmx.note.*: debug
# mybatis-puls ??
mybatis-plus:
  # ??mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??mybatis??????????????
  type-aliases-package: com.lxm.note
server:
  port: 8002