spring:
#  web:
#    resources:
#      add-mappings: true
#      static-locations: classpath:/static/
  application:
    name: API
  cloud:
    zookeeper:
      discovery:
        register: false
        enabled: true
      connect-string: localhost:2181
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
logging:
  level:
    com.lmx.api.controller.*: debug